### ISSUE TITLE
Syrmorite Bucket Quest

### ISSUE THREAD

**Issue by Gh0stic** [Team8BitOrg/may-pack-c2a#1]
Thank you for submitting an issue report. Please provide as much information as possible and please complete all sections.
*NOTE: As you are reporting a bug, please upload the log to an online service (PasteBin/Gist/Pastee/Etc) and share the link in the appropriate location below.*

## **Game Information**
* What mode were you playing in when the issue arose? Survival Multiplayer
* Is there any other game information that might be related?

## **Bug Report**
Please describe the current behavior in detail. Have you attempted to reproduce the bug? when making Syrmorite Bucket using the steps in the quest, the bucket does successfully work but the quest doesn't trigger complete when bucket is picked up.

## **Expected Behavior**
If describing a bug, what happens instead of the expected behavior? FTB quest to recognize the bucket being picked up and progress the quest.

## **Possible Solution**
Do you have a suggestion for a fix/reason for the bug? Maybe a quest trigger issue.

## **Steps to Reproduce**
Provide a link to a live example, or an unambiguous set of steps to reproduce the issue
1. I followed the exact quest step to complete the quest.

## **Client Information**
Please provide as much information as possible about your setup when experiencing this issue.
* Modpack Version: 1.0.1-hotfix
* Java Version: 8
* Launcher Used: GDLauncher
* Memory Allocated: 8GB
* Server/LAN/Single Player: 7C's Server
* Optifine Installed: None
* Shaders Enabled: None

**Comment by PseudoFyre** [comment]
Turns out that you have to pick up some liquid with the bucket and then replace it and the quest triggers. This could be something to do with how forge works or how FTB Quests works.
